using System;
using System.Text;
using Leopotam.EcsLite;
using UnityCodeGen;
using UnityEditor;

public class EcsSystemAttribute : Attribute
{
}


[Generator]
public class EcsSystemsCollectionGenerator : ICodeGenerator
{
    public void Execute(GeneratorContext context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Leopotam.EcsLite;");
        sb.AppendLine("public static class EcsSystemsCollection");
        sb.AppendLine("{");
        sb.AppendLine("public static void Add(EcsSystems systems)");
        sb.AppendLine("{");

        var types = TypeCache.GetTypesWithAttribute<EcsSystemAttribute>();
        foreach (var type in types)
        {
            var name = type.FullName;
            sb.AppendLine("systems.Add(new " + name + "());");
        }

        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddCode("EcsSystemsCollection.Generated.cs", sb.ToString());
    }
}