using System.Text;
using SevenBoldPencil.EasyEvents.EcsDemo;
using UnityCodeGen;
using UnityEditor;

[Generator]
public class NetworkEventDestroyGenerator : ICodeGenerator
{
    public void Execute(GeneratorContext context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Leopotam.EcsLite;");
        sb.AppendLine("using SevenBoldPencil.EasyEvents;");
        sb.AppendLine("public static class NetworkEventDestroy");
        sb.AppendLine("{");
        sb.AppendLine("public static void Add(EcsSystems systems, EventsBus eventsBus)");
        sb.AppendLine("{");

        sb.AppendLine("systems.Add(eventsBus.GetDestroyEventsSystem()");
        var types = TypeCache.GetTypesWithAttribute<NetworkEventAttribute>();
        foreach (var type in types)
        {
            sb.AppendLine($".IncReplicant<{type.FullName}>()");
        }

        sb.AppendLine(");");

        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddCode("NetworkEventDestroy.Generated.cs", sb.ToString());
    }
}