using System.Text;
using UnityCodeGen;
using UnityEditor;
using UnityEngine;

namespace SevenBoldPencil.EasyEvents.EcsDemo
{
    [Generator]
    public class NetworkWorldPlayerEventsGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Mirror;");
            sb.AppendLine("public partial class NetworkWorldPlayer : NetworkBehaviour");
            sb.AppendLine("{");
            var types = TypeCache.GetTypesWithAttribute<NetworkEventAttribute>();
            foreach (var type in types)
            {
                var name = type.FullName;
                sb.AppendLine("[Command]");
                sb.AppendLine($"public void CmdSendNetworkEvent({name} @event)");
                sb.AppendLine("{");
                sb.AppendLine("OnServerReceiveEvent(@event);");
                sb.AppendLine("}");
            }

            sb.AppendLine("}");

            context.AddCode("NetworkWorldPlayer.Events.Generated.cs", sb.ToString());
        }
    }
}