using UnityCodeGen;

[Generator] // Add GeneratorAttribute
public class SampleGenerator : ICodeGenerator // Inherits ICodeGenerator
{
    public void Execute(GeneratorContext context) // Implement Execute method
    {
        context.AddCode("Sample.Generated.cs", // File name
            @"// <auto-generated/>
namespace SampleNamespace.Generated
{
    public class Sample
    {

    }
}"
        );
    }
}