// <auto-generated/>
using Leopotam.EcsLite;
public static class EcsSystemsCollection
{
public static void Add(EcsSystems systems)
{
systems.Add(new RemoveVersionComponentSystem());
systems.Add(new TestEventSystem());
systems.Add(new TestRecoverSystem());
}
}
