// <auto-generated/>
using Mirror;
public static class NetworkEventExtensions {
public static void SendNetworkEvent(this IWorld world, TestEvent @event){
                    NetworkClient.localPlayer.GetComponent<NetworkWorldPlayer>().CmdSendNetworkEvent(@event);
                }
}
