// <auto-generated/>
using Leopotam.EcsLite;
using SevenBoldPencil.EasyEvents;
public static class NetworkEventDestroy
{
public static void Add(EcsSystems systems, EventsBus eventsBus)
{
systems.Add(eventsBus.GetDestroyEventsSystem()
.IncReplicant<TestEvent>()
);
}
}
