// <auto-generated/>
using Leopotam.EcsLite;
public partial class SystemAutoCollect : SystemAutoCollectBase
{
public override void AddAutoCollectSystems(EcsSystems systems)
{
systems.Add(new TestEventSystem());
}
}
